version: '3.6'

services:
  gap:
    build: ./gap
    ports:
      - "26133:26133"
  
  mmt:
    build: ./mmt
    volumes:
      - mmt:/content/
    ports:
      - "26134:26134"
  
  singular:
    build: ./singular
    ports:
      - "26135:26135"
  
  sage:
    build: ./sage
    ports:
      - "26136:26133"

volumes:
  mmt:
